### ISSUE TITLE
Crash on export

### ISSUE THREAD

**Issue by Serentty** [lriecken/Vera-Graphics-Converter#1]
I'm having an issue where I can't export any image at all without it crashing. Someone else on the Commander X16 website seems to be having the same problem. I don't get any error message with a call stack or anything to share here. It just closes.

**Comment by lriecken** [comment]
Thanks for the info. The project isn't abandoned, I plan to update it in the coming months when there is news about the Commander X16 and the VERA is finalized. I feel the emulator spoils all the fun, so I'm not looking at the Project right now.

This bug occurs because the "SplitFiles at" variable isn't set. As a workaround, open File/Settings before exporting.

**Comment by Serentty** [comment]
Thanks! That's very helpful. Apparently the VERA is only getting bugfixes now, so we're getting closer to it being ready for release. As for the actual manufacturing, that's yet to be seen.
